const testlist = [
  {
    title: '1번글',
    owner: '임승진',
    writes:
      '1번글 본문임 근데 좀 많이 이상한 1번글 본문임 근데 좀 많이 이상한 1번글 본문임 근데 좀 많이 이상한\n1번글 본문임 근데 좀 많이 이상한 1번글 본문임 근데 좀 많이 이상한 1번글 본문임 근데 좀 많이 이상한',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 1,
    id: 1,
  },
  {
    title: '2번글',
    owner: '임승진진',
    writes: '2번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 2,
    id: 2,
  },
  {
    title: '3번글',
    owner: '임승진진진',
    writes: '3번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 3,
    id: 3,
  },
  {
    title: '4번글',
    owner: '임승진진진진',
    writes: '4번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 3,
    id: 4,
  },
  {
    title: '5번글',
    owner: '임승진진진진진',
    writes: '5번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 4,
    id: 5,
  },
  {
    title: '6번글',
    owner: '임승진진진진진',
    writes: '6번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 4,
    id: 6,
  },
  {
    title: '7번글',
    owner: '임승진진진진진',
    writes: '7번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 4,
    id: 7,
  },
  {
    title: '8번글',
    owner: '임승진진진진진',
    writes: '8번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 4,
    id: 8,
  },
  {
    title: '9번글',
    owner: '임승진진진진진',
    writes: '9번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 4,
    id: 9,
  },
  {
    title: '10번글',
    owner: '임승진진진진진',
    writes: '10번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 4,
    id: 10,
  },
  {
    title: '11번글',
    owner: '임승진진진진진',
    writes: '11번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 4,
    id: 11,
  },
]

export default testlist
