const testlist = [
  {
    title: '1번글',
    owner: '임승진',
    writes: '1번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 1,
    id: 0,
  },
  {
    title: '2번글',
    owner: '임승진진',
    writes: '2번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 2,
    id: 1,
  },
  {
    title: '3번글',
    owner: '임승진진진',
    writes: '3번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 3,
    id: 2,
  },
  {
    title: '4번글',
    owner: '임승진진진진',
    writes: '4번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 3,
    id: 3,
  },
  {
    title: '5번글',
    owner: '임승진진진진진',
    writes: '5번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 4,
    id: 4,
  },
  {
    title: '6번글',
    owner: '임승진진진진진',
    writes: '6번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 4,
    id: 4,
  },
  {
    title: '7번글',
    owner: '임승진진진진진',
    writes: '7번글 본문임',
    updated_at: '수정 없는데',
    create_at: '어제',
    own: 4,
    id: 4,
  },
]

export default testlist
